### ISSUE TITLE
Changes to as_date in lubridate v1.7.0 create error

### ISSUE THREAD

**Issue by steffilazerte** [steffilazerte/weathercan#41]

**Comment by ebourlon** [comment]
Thank. I tried to change the as_date for other function but was not knowing ymd. This edit was working yesterday... but this morning I now have another issue on the same lines. The error says:
Error in mutate_impl(.data, dots) : 
  Evaluation error: 'origin' must be supplied.
Has the command ymd changed overnight?

**Comment by ebourlon** [comment]
The weathercan v0.2.2  is still working ok.

**Comment by steffilazerte** [comment]
Most of these changes haven't been pushed to the master branch yet, as we're still trying to fix some underlying issues. `ymd` is from the lubridate package and it's behaviour may change with the package version of lubridate you have. We're still troubleshooting at the moment, hopefully it'll be fixed soon!

**Comment by ebourlon** [comment]
Thank you so much. We depend a lot on your packages to get our weather data
for plume dispersion modeling. Some computers were not updated so we are
still good.
I'll try things on thevweater script on my side as well.
Cheers,
Evelise

**Comment by ebourlon** [comment]
Good morning Steffi,
The new lubricate package does not create any error 😀
Thank for Weather can.  It's such a great package.
Have a nice day,
Evelise

**Comment by steffilazerte** [comment]
Glad to hear it! lubridate was just updated on cran to fix some of the bugs that we were experiencing so hopefully this isn't an issue any more.
