### ISSUE TITLE
Attempt to remove sp dependency

### ISSUE THREAD

**Issue by boshek** [steffilazerte/weathercan#45]
The overhead for these two lines is pretty significant:
 
https://github.com/steffilazerte/weathercan/blob/a5948a687df58b65657a3b0e61a813812d4095d3/R/stations.R#L190-L191
 
Particularly for mac and linux this requires installing quite a lot of other material. We should try to remove it.

**Comment by steffilazerte** [comment]
That's a very good point. Will have to look into it.
